name: add2-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - evidently
  - lightgbm
  - missingno
  - shap
  - jupyterlab
  - scikit-learn
  - xgboost
  - ipykernel
  - lime
  - umap-learn
  - scipy
  - ipywidgets
  - seaborn
  - matplotlib
  - imbalanced-learn
  - great-expectations
  - pyod
  - hdbscan
  - featuretools
  - category_encoders
  - opentsne
  - feature_engine
  - aif360
  - fairlearn
  - pillow
  - pip
  - pip:
    - alibi
    - aequitasy